#!/bin/bash

repos=(
  'https://github.com/scrooloose/nerdtree.git'
  'https://github.com/hdima/python-syntax.git'
  'https://github.com/elzr/vim-json.git'
  'https://github.com/fatih/vim-go.git'
)

pushd $HOME/.vim/bundle

for i in $repos; do
  grep "$i" */.git/config &>/dev/null || git clone $i
done
