#!/bin/bash

bg=Pictures/wallpapers/169/alena-aenami-sundown.jpg
feh --bg-max $bg

laptopscreen=eDP-1

if [ $GDMSESSION == "i3" ]; then
   i3-msg "[workspace=\"^(1|2|3|4|5|6|7|8|9|10)\"] move workspace to output $laptopscreen;"
fi

if [ $GDMSESSION == "bspwm" ]; then
   bspc monitor $laptopscreen -d 1 2 3 4 5 6 7 8 9 10
fi

lockscreen_bg=/tmp/lockscreen_bg

convert $bg -resize 1920x1080\! $lockscreen_bg
betterlockscreen -u $lockscreen_bg &
