#!/bin/bash

bg=Pictures/wallpapers/169/alena-aenami-sundown.jpg
feh --bg-max $bg

laptopscreen=eDP-1

if [ $GDMSESSION == "i3" ]; then
   i3-msg "[workspace=\"^(1|2|3|4|5|6|7|8|9|10)\"] move workspace to output $laptopscreen;"
fi

if [ $GDMSESSION == "bspwm" ]; then

   bspc desktop 1  --to-monitor $laptopscreen --follow
   bspc desktop 2  --to-monitor $laptopscreen --follow
   bspc desktop 3  --to-monitor $laptopscreen --follow
   bspc desktop 4  --to-monitor $laptopscreen --follow
   bspc desktop 5  --to-monitor $laptopscreen --follow
   bspc desktop 6  --to-monitor $laptopscreen --follow
   bspc desktop 7  --to-monitor $laptopscreen --follow
   bspc desktop 8  --to-monitor $laptopscreen --follow
   bspc desktop 9  --to-monitor $laptopscreen --follow
   bspc desktop 10 --to-monitor $laptopscreen --follow
   bspc monitor $laptopscreen --reorder-desktops 1 2 3 4 5 6 7 8 9 10
fi

cache_path="$HOME/.cache/lockscreen"
[ -d $cache_path ] || mkdir -p $cache_path
lockscreen_bg="$cache_path/lockscreen_bg_$AUTORANDR_CURRENT_PROFILE"

if [ ! -f $lockscreen_bg ]
then

   convert $bg -resize 1920x1080\! $lockscreen_bg
   $HOME/bin/betterlockscreen_mm -u $lockscreen_bg &

fi
