#!/bin/bash
debug=false

usage() {
	echo 'Extend dot files'
	echo
	echo 'Options:'
	echo
	echo '	-h --help'
	echo '		For help.'
	echo
	echo
	echo '	-b --bashrc'
	echo '		extend .bashrc file'
	echo
	echo
	echo '	-p --profile'
	echo '		extend .profile file'
}

extend_execute() {
   local extend_path=$1

   [ "$debug" = true ] && echo "extend_execute"
   if [ -d "$extend_path" ]; then
      [ $debug = true ] && echo "$extend_path found"
      for f in "$extend_path"/*; do
         [ $debug = true ] && echo "execute $f"
         [ -x "$f" ] && $f
      done
      unset f
   else
      echo "$extend_path not found"
   fi
}

extend_source() {
   local extend_path=$1

   [ "$debug" = true ] && echo "extend_source"
   if [ -d "$extend_path" ] ; then
      [ "$debug" = true ] && echo "$extend_path found"
      for f in "$extend_path"/* ; do
          [ "$debug" = true ] && echo "source $f"
         [ -x "$f" ] && . "$f"
      done
      unset f
   else
      echo "$extend_path not found"
   fi
}

# Options
[[ "$1" = '' ]] && usage

for arg in "$@"; do
	[[ "${arg:0:1}" = '-' ]] || continue

	case "$1" in
		-h | --help)
			usage
			break
			;;

		-b | --bashrc)
         extend_source $HOME/.config/extend-rc/bashrc.d
         break
			;;

		-p | --profile)
         extend_execute $HOME/.config/extend-rc/profile.d
         break
			;;

		*)
			echo "invalid argument: $1"
			break
			;;
	esac
done


