#!/bin/bash

leftscreen=HDMI-1
laptopscreen=eDP-1

if [ $GDMSESSION == "i3" ]; then
   i3-msg "[workspace=\"^(8|9|10)\"] move workspace to output $laptopscreen;"
   i3-msg "[workspace=\"^(1|2|3|4|5|6|7)\"] move workspace to output $leftscreen;"
fi

if [ $GDMSESSION == "bspwm" ]; then
   bspc monitor $leftscreen   -d 1 2 3 4 5 6 7  
   bspc monitor $laptopscreen -d 8 9 10
fi

bg_left=Pictures/wallpapers/ultrawide/longque-chen-space-investigation.jpg
bg_laptop=Pictures/wallpapers/169/alena-aenami-sundown.jpg

feh --bg-max $bg_left $bg_laptop 

cache_path="$HOME/.cache/lockscreen"
[ -d $cache_path ] || mkdir -p $cache_path
lockscreen_bg="$cache_path/lockscreen_bg_$AUTORANDR_CURRENT_PROFILE"

if [ ! -f $lockscreen_bg ]
then
   convert \
      \( $bg_left -resize 3440x1440\! -background black -gravity center -extent 3440x1440 \) \
      \( $bg_laptop -resize 1920x1080\! -background black -gravity south -extent 1920x1440 \) \
       +append $lockscreen_bg
   #convert $bg_left -background black -gravity center -extent 3440x1440 $bg_left_scaled
   #convert $bg_laptop -background black -gravity south -extent 1920x1440 $bg_laptop_scaled
   #convert $bg_left_scaled $bg_laptop_scaled +append $lockscreen_bg
fi

$HOME/bin/betterlockscreen_mm -u $lockscreen_bg --span &
