#!/bin/bash

feh --bg-max Pictures/wallpapers/Ultrawide/Saturn\ as\ seen\ from\ Lapetus\ \(Vincent\ Di\ Fate\)\ \[2560x1080\].png Pictures/wallpapers/alena-aenami-eclipse-1k.jpg Pictures/wallpapers/alena-aenami-aenami-lunar.jpg
