#! /bin/sh

sxhkd -c $HOME/.config/bspwm/sxhkdrc &
autorandr --change --force &

primary_monitor=$(xrandr --query | grep " primary" | cut -d" " -f1)
bspc monitor $primary_monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config normal_border_color  "#2d384d"
bspc config focused_border_color "#ffcc66"
bspc config active_border_color  "#3c526a"

bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^10' state=floating follow=on
bspc rule -a Chromium desktop='^8'
bspc rule -a Mattermost desktop='^8'
bspc rule -a Slack desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
