#! /bin/sh

#### AUTOSTART ####
$HOME/.config/autostart.sh
$HOME/.config/polybar/launch.sh 2>$HOME/.config/polybar/errors.log
sxhkd &

#### WORKSPACES AND BORDERS #### 

#Monitor allocation and their workspaces
bspc monitor DP-1 -d 1 2 3 4
bspc monitor DVI-I-1 -d 6 7 8 9 10
bspc monitor DVI-D-0 -d 5

#Border gaps,width, and padding
bspc config border_width         0
bspc config window_gap          25
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding 		 20

#bspc rule -a URxvt desktop='^1' follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a Evince desktop='^5'follow=on

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

